# Generated by Django 5.2.13 on 2026-04-28 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('ku_digital_signature', models.BooleanField(default=False)),
                ('ku_non_repudiation', models.BooleanField(default=False)),
                ('ku_key_encipherment', models.BooleanField(default=False)),
                ('ku_data_encipherment', models.BooleanField(default=False)),
                ('ku_key_agreement', models.BooleanField(default=False)),
                ('ku_key_cert_sign', models.BooleanField(default=False)),
                ('ku_crl_sign', models.BooleanField(default=False)),
                ('ku_encipher_only', models.BooleanField(default=False)),
                ('ku_decipher_only', models.BooleanField(default=False)),
                ('ku_critical', models.BooleanField(default=True, help_text='RFC 5280: MUST be critical')),
                ('eku', models.TextField(blank=True, default='', help_text='Comma-separated: serverAuth, clientAuth, codeSigning, emailProtection, timeStamping, OCSPSigning, or raw OIDs like 1.3.6.1.5.5.7.3.8')),
                ('eku_critical', models.BooleanField(default=False)),
                ('extra_extensions', models.TextField(blank=True, help_text='Raw openssl.cnf extension lines, one per line (e.g. tlsfeature = status_request)')),
                ('name_constraints_permitted', models.TextField(blank=True, default='', help_text='Permitted subtrees (one entry per line, e.g. DNS:.example.org).')),
                ('name_constraints_excluded', models.TextField(blank=True, default='', help_text='Excluded subtrees (one entry per line, e.g. DNS:.bad.example.org).')),
                ('name_constraints_critical', models.BooleanField(default=True)),
                ('policy_constraints_require_explicit', models.IntegerField(blank=True, help_text='requireExplicitPolicy (≥0). Empty = not present.', null=True)),
                ('policy_constraints_inhibit_mapping', models.IntegerField(blank=True, help_text='inhibitPolicyMapping (≥0). Empty = not present.', null=True)),
                ('inhibit_any_policy', models.IntegerField(blank=True, help_text='SkipCerts integer for inhibitAnyPolicy. Empty = not present.', null=True)),
                ('crl_url', models.CharField(blank=True, default='', help_text='Profile-level CRL URL — overrides the CA value when set.', max_length=512)),
                ('aia_url', models.CharField(blank=True, default='', help_text='Profile-level caIssuers URL — overrides the CA value when set.', max_length=512)),
                ('ocsp_url', models.CharField(blank=True, default='', help_text='Profile-level OCSP responder URL — overrides the CA value when set.', max_length=512)),
                ('sia_url', models.CharField(blank=True, default='', help_text='Profile-level Subject Information Access URL — overrides the CA value when set.', max_length=512)),
                ('freshest_crl_url', models.CharField(blank=True, default='', help_text='Profile-level delta-CRL URL — overrides the CA value when set.', max_length=512)),
                ('include_subject_key_identifier', models.BooleanField(default=True)),
                ('include_authority_key_identifier', models.BooleanField(default=True)),
                ('aki_include_issuer', models.BooleanField(default=False, help_text='Add issuer:always to authorityKeyIdentifier.')),
                ('custom_oid_fields', models.JSONField(blank=True, default=list, help_text='DEPRECATED. Legacy JSON custom OID fields.')),
                ('is_ca_profile', models.BooleanField(default=False, help_text='If True, basicConstraints = CA:TRUE (for intermediate CA certs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Profile',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomOidDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, default='', help_text='Dotted OID (e.g. 1.2.643.100.3). Empty for built-in SAN types (DNS, IP, email, URI).', max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('asn1_type', models.CharField(choices=[('UTF8', 'UTF8String'), ('IA5', 'IA5String'), ('PRINTABLE', 'PrintableString'), ('INT', 'INTEGER'), ('BOOL', 'BOOLEAN')], default='UTF8', max_length=16)),
                ('placement', models.CharField(choices=[('extension', 'Extension'), ('san_dns', 'SAN DNS name'), ('san_ip', 'SAN IP address'), ('san_email', 'SAN email'), ('san_uri', 'SAN URI'), ('san_othername', 'SAN otherName')], default='extension', max_length=24)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in definitions cannot be deleted via UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom OID Definition',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_cert_profile_protection', models.BooleanField(default=False, help_text='When enabled, any role can submit a free-form certificate request bypassing the cert-profile constraints (KU, EKU, extensions, OIDs).')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ca_type', models.CharField(choices=[('root', 'Root CA'), ('intermediate', 'Intermediate CA')], default='root', max_length=16)),
                ('subject', models.CharField(max_length=512)),
                ('key_alg', models.CharField(choices=[('gost2012_256', 'GOST R 34.10-2012 (256 bit)'), ('gost2012_512', 'GOST R 34.10-2012 (512 bit)'), ('rsa:2048', 'RSA 2048'), ('rsa:4096', 'RSA 4096'), ('ec:P-256', 'ECDSA P-256 (secp256r1)'), ('ec:P-384', 'ECDSA P-384 (secp384r1)'), ('ed25519', 'Ed25519')], default='gost2012_256', max_length=32)),
                ('serial_hex', models.CharField(blank=True, max_length=64)),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=128)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('crl_url', models.CharField(blank=True, help_text='CRL Distribution Point URL embedded in issued certs', max_length=512)),
                ('aia_url', models.CharField(blank=True, help_text='Authority Info Access caIssuers URL embedded in issued certs', max_length=512)),
                ('ocsp_url', models.CharField(blank=True, default='', help_text='OCSP responder URL embedded as authorityInfoAccess OCSP entry (RFC 6960).', max_length=512)),
                ('sia_url', models.CharField(blank=True, default='', help_text='Subject Information Access URL — caRepository for sub-CAs (RFC 5280 §4.2.2.2).', max_length=512)),
                ('freshest_crl_url', models.CharField(blank=True, default='', help_text='URL of delta CRL (freshestCRL extension, RFC 5280 §4.2.1.15).', max_length=512)),
                ('issuer_alt_names', models.TextField(blank=True, default='', help_text='issuerAltName entries embedded in issued certs (one per line, e.g. email:ca@example.org).')),
                ('is_enabled', models.BooleanField(default=True)),
                ('require_otp_for_issuance', models.BooleanField(default=False, help_text='Require TOTP code from operator before issuing certificates under this CA.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dashboard.certificateauthority')),
                ('cert_profiles', models.ManyToManyField(blank=True, help_text='Certificate profiles available for issuance under this CA. Empty = no profiles available for operators.', limit_choices_to={'is_ca_profile': False}, related_name='allowed_cas', to='dashboard.certprofile')),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=512)),
                ('serial_hex', models.CharField(db_index=True, max_length=64)),
                ('profile_name', models.CharField(blank=True, help_text='Snapshot of profile display_name at issue time', max_length=128)),
                ('custom_oid_values', models.JSONField(blank=True, default=dict, help_text='Snapshot of custom OID values at issue time: {oid: value}')),
                ('key_alg', models.CharField(choices=[('gost2012_256', 'GOST R 34.10-2012 (256 bit)'), ('gost2012_512', 'GOST R 34.10-2012 (512 bit)'), ('rsa:2048', 'RSA 2048'), ('rsa:4096', 'RSA 4096'), ('ec:P-256', 'ECDSA P-256 (secp256r1)'), ('ec:P-384', 'ECDSA P-384 (secp384r1)'), ('ed25519', 'Ed25519')], default='gost2012_256', max_length=32)),
                ('san_dns', models.TextField(blank=True, help_text='Comma- or newline-separated DNS names')),
                ('san_ip', models.TextField(blank=True, help_text='Comma- or newline-separated IPs')),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=128)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('has_private_key', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('keyCompromise', 'Key compromise'), ('CACompromise', 'CA compromise'), ('affiliationChanged', 'Affiliation changed'), ('superseded', 'Superseded'), ('cessationOfOperation', 'Cessation of operation'), ('certificateHold', 'Certificate hold')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_from', models.ForeignKey(blank=True, help_text='Original certificate this one was renewed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='dashboard.certificate')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested this certificate (null for pre-RBAC or operator-initiated certs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_certificates', to=settings.AUTH_USER_MODEL)),
                ('issuer_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='dashboard.certificateauthority')),
                ('cert_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='dashboard.certprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('key_alg', models.CharField(choices=[('gost2012_256', 'GOST R 34.10-2012 (256 bit)'), ('gost2012_512', 'GOST R 34.10-2012 (512 bit)'), ('rsa:2048', 'RSA 2048'), ('rsa:4096', 'RSA 4096'), ('ec:P-256', 'ECDSA P-256 (secp256r1)'), ('ec:P-384', 'ECDSA P-384 (secp384r1)'), ('ed25519', 'Ed25519')], default='gost2012_256', max_length=32)),
                ('san_dns', models.TextField(blank=True)),
                ('san_ip', models.TextField(blank=True)),
                ('days', models.IntegerField(default=365)),
                ('csr_pem', models.TextField(blank=True, help_text='PEM-encoded CSR uploaded by the user')),
                ('notes', models.TextField(blank=True, help_text='User notes for the operator')),
                ('is_free_form', models.BooleanField(default=False, help_text='Free-form request bypassing cert-profile constraints — extension lines, SAN entries, and DP overrides are stored in free_form_data.')),
                ('free_form_data', models.JSONField(blank=True, default=dict, help_text='Self-contained payload for free-form requests. Keys: "ext_lines" (list[str]), "san_email"/"san_uri"/"san_other" (list[str]), "crl_url"/"aia_url"/"ocsp_url"/"sia_url"/"freshest_crl_url" (str, blank = inherit from CA).')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='dashboard.certificate')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('cert_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_requests', to='dashboard.certprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrlExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('crl_number', models.CharField(blank=True, max_length=64)),
                ('revoked_count', models.IntegerField(default=0)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crl_exports', to='dashboard.certificateauthority')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileOidField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('oid_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_usages', to='dashboard.customoiddefinition')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_oid_fields', to='dashboard.certprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'unique_together': {('profile', 'oid_definition')},
            },
        ),
        migrations.AddField(
            model_name='certprofile',
            name='oid_fields',
            field=models.ManyToManyField(blank=True, help_text='OID field definitions assigned to this profile.', through='dashboard.ProfileOidField', to='dashboard.customoiddefinition'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_cidrs', models.TextField(blank=True, help_text='One CIDR per line (e.g. 10.0.0.0/8). Empty = allow from any IP.')),
                ('auth_methods', models.CharField(default='password', help_text='Comma-separated list of enabled auth methods (password, mtls, otp).', max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cas', models.ManyToManyField(blank=True, help_text='CAs this operator can use. Empty = no access to any CA.', related_name='assigned_operators', to='dashboard.certificateauthority')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
