# Generated by Django 5.2.13 on 2026-04-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seed_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateauthority',
            name='cert_profiles',
        ),
    ]
