# Generated by Django 5.2.14 on 2026-05-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_certificateauthority_cert_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_ecdsa_keys',
            field=models.BooleanField(default=False, help_text='Allow ECDSA (P-256, P-384) and Ed25519 key families.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_gost_keys',
            field=models.BooleanField(default=True, help_text='Allow GOST R 34.10-2012 key families. Requires OWNCA_GOST_ENGINE=on.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_rsa_keys',
            field=models.BooleanField(default=True, help_text='Allow RSA key families.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_server_key_generation',
            field=models.BooleanField(default=True, help_text='When disabled, server-side key generation is refused; only externally supplied CSRs are accepted.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='offer_gost_p12_export',
            field=models.BooleanField(default=True, help_text='Offer TK-26 compatible .gost.p12 export option (RFC 9337/9548). Requires GOST keys to be enabled.'),
        ),
    ]
